//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conexion3.ServiceWeb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/webservice", ConfigurationName="ServiceWeb.WebServicePruebaSoap")]
    public interface WebServicePruebaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservice/openConexion", ReplyAction="*")]
        Conexion3.ServiceWeb.openConexionResponse openConexion(Conexion3.ServiceWeb.openConexionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservice/openConexion", ReplyAction="*")]
        System.Threading.Tasks.Task<Conexion3.ServiceWeb.openConexionResponse> openConexionAsync(Conexion3.ServiceWeb.openConexionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservice/closeConexion", ReplyAction="*")]
        Conexion3.ServiceWeb.closeConexionResponse closeConexion(Conexion3.ServiceWeb.closeConexionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservice/closeConexion", ReplyAction="*")]
        System.Threading.Tasks.Task<Conexion3.ServiceWeb.closeConexionResponse> closeConexionAsync(Conexion3.ServiceWeb.closeConexionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Name del espacio de nombres http://localhost/webservice no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservice/insertarDrugstore", ReplyAction="*")]
        Conexion3.ServiceWeb.insertarDrugstoreResponse insertarDrugstore(Conexion3.ServiceWeb.insertarDrugstoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservice/insertarDrugstore", ReplyAction="*")]
        System.Threading.Tasks.Task<Conexion3.ServiceWeb.insertarDrugstoreResponse> insertarDrugstoreAsync(Conexion3.ServiceWeb.insertarDrugstoreRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Employee_Id del espacio de nombres http://localhost/webservice no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservice/personaRegistrada", ReplyAction="*")]
        Conexion3.ServiceWeb.personaRegistradaResponse personaRegistrada(Conexion3.ServiceWeb.personaRegistradaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservice/personaRegistrada", ReplyAction="*")]
        System.Threading.Tasks.Task<Conexion3.ServiceWeb.personaRegistradaResponse> personaRegistradaAsync(Conexion3.ServiceWeb.personaRegistradaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class openConexionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="openConexion", Namespace="http://localhost/webservice", Order=0)]
        public Conexion3.ServiceWeb.openConexionRequestBody Body;
        
        public openConexionRequest() {
        }
        
        public openConexionRequest(Conexion3.ServiceWeb.openConexionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservice")]
    public partial class openConexionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string error;
        
        public openConexionRequestBody() {
        }
        
        public openConexionRequestBody(string error) {
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class openConexionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="openConexionResponse", Namespace="http://localhost/webservice", Order=0)]
        public Conexion3.ServiceWeb.openConexionResponseBody Body;
        
        public openConexionResponse() {
        }
        
        public openConexionResponse(Conexion3.ServiceWeb.openConexionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservice")]
    public partial class openConexionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool openConexionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string error;
        
        public openConexionResponseBody() {
        }
        
        public openConexionResponseBody(bool openConexionResult, string error) {
            this.openConexionResult = openConexionResult;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class closeConexionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="closeConexion", Namespace="http://localhost/webservice", Order=0)]
        public Conexion3.ServiceWeb.closeConexionRequestBody Body;
        
        public closeConexionRequest() {
        }
        
        public closeConexionRequest(Conexion3.ServiceWeb.closeConexionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservice")]
    public partial class closeConexionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string error;
        
        public closeConexionRequestBody() {
        }
        
        public closeConexionRequestBody(string error) {
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class closeConexionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="closeConexionResponse", Namespace="http://localhost/webservice", Order=0)]
        public Conexion3.ServiceWeb.closeConexionResponseBody Body;
        
        public closeConexionResponse() {
        }
        
        public closeConexionResponse(Conexion3.ServiceWeb.closeConexionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservice")]
    public partial class closeConexionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string error;
        
        public closeConexionResponseBody() {
        }
        
        public closeConexionResponseBody(string error) {
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarDrugstoreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarDrugstore", Namespace="http://localhost/webservice", Order=0)]
        public Conexion3.ServiceWeb.insertarDrugstoreRequestBody Body;
        
        public insertarDrugstoreRequest() {
        }
        
        public insertarDrugstoreRequest(Conexion3.ServiceWeb.insertarDrugstoreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservice")]
    public partial class insertarDrugstoreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string thelephone;
        
        public insertarDrugstoreRequestBody() {
        }
        
        public insertarDrugstoreRequestBody(string Name, string thelephone) {
            this.Name = Name;
            this.thelephone = thelephone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarDrugstoreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarDrugstoreResponse", Namespace="http://localhost/webservice", Order=0)]
        public Conexion3.ServiceWeb.insertarDrugstoreResponseBody Body;
        
        public insertarDrugstoreResponse() {
        }
        
        public insertarDrugstoreResponse(Conexion3.ServiceWeb.insertarDrugstoreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservice")]
    public partial class insertarDrugstoreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertarDrugstoreResult;
        
        public insertarDrugstoreResponseBody() {
        }
        
        public insertarDrugstoreResponseBody(string insertarDrugstoreResult) {
            this.insertarDrugstoreResult = insertarDrugstoreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class personaRegistradaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="personaRegistrada", Namespace="http://localhost/webservice", Order=0)]
        public Conexion3.ServiceWeb.personaRegistradaRequestBody Body;
        
        public personaRegistradaRequest() {
        }
        
        public personaRegistradaRequest(Conexion3.ServiceWeb.personaRegistradaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservice")]
    public partial class personaRegistradaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Employee_Id;
        
        public personaRegistradaRequestBody() {
        }
        
        public personaRegistradaRequestBody(string Employee_Id) {
            this.Employee_Id = Employee_Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class personaRegistradaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="personaRegistradaResponse", Namespace="http://localhost/webservice", Order=0)]
        public Conexion3.ServiceWeb.personaRegistradaResponseBody Body;
        
        public personaRegistradaResponse() {
        }
        
        public personaRegistradaResponse(Conexion3.ServiceWeb.personaRegistradaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservice")]
    public partial class personaRegistradaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int personaRegistradaResult;
        
        public personaRegistradaResponseBody() {
        }
        
        public personaRegistradaResponseBody(int personaRegistradaResult) {
            this.personaRegistradaResult = personaRegistradaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicePruebaSoapChannel : Conexion3.ServiceWeb.WebServicePruebaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicePruebaSoapClient : System.ServiceModel.ClientBase<Conexion3.ServiceWeb.WebServicePruebaSoap>, Conexion3.ServiceWeb.WebServicePruebaSoap {
        
        public WebServicePruebaSoapClient() {
        }
        
        public WebServicePruebaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicePruebaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePruebaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePruebaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Conexion3.ServiceWeb.openConexionResponse Conexion3.ServiceWeb.WebServicePruebaSoap.openConexion(Conexion3.ServiceWeb.openConexionRequest request) {
            return base.Channel.openConexion(request);
        }
        
        public bool openConexion(ref string error) {
            Conexion3.ServiceWeb.openConexionRequest inValue = new Conexion3.ServiceWeb.openConexionRequest();
            inValue.Body = new Conexion3.ServiceWeb.openConexionRequestBody();
            inValue.Body.error = error;
            Conexion3.ServiceWeb.openConexionResponse retVal = ((Conexion3.ServiceWeb.WebServicePruebaSoap)(this)).openConexion(inValue);
            error = retVal.Body.error;
            return retVal.Body.openConexionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Conexion3.ServiceWeb.openConexionResponse> Conexion3.ServiceWeb.WebServicePruebaSoap.openConexionAsync(Conexion3.ServiceWeb.openConexionRequest request) {
            return base.Channel.openConexionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Conexion3.ServiceWeb.openConexionResponse> openConexionAsync(string error) {
            Conexion3.ServiceWeb.openConexionRequest inValue = new Conexion3.ServiceWeb.openConexionRequest();
            inValue.Body = new Conexion3.ServiceWeb.openConexionRequestBody();
            inValue.Body.error = error;
            return ((Conexion3.ServiceWeb.WebServicePruebaSoap)(this)).openConexionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Conexion3.ServiceWeb.closeConexionResponse Conexion3.ServiceWeb.WebServicePruebaSoap.closeConexion(Conexion3.ServiceWeb.closeConexionRequest request) {
            return base.Channel.closeConexion(request);
        }
        
        public void closeConexion(ref string error) {
            Conexion3.ServiceWeb.closeConexionRequest inValue = new Conexion3.ServiceWeb.closeConexionRequest();
            inValue.Body = new Conexion3.ServiceWeb.closeConexionRequestBody();
            inValue.Body.error = error;
            Conexion3.ServiceWeb.closeConexionResponse retVal = ((Conexion3.ServiceWeb.WebServicePruebaSoap)(this)).closeConexion(inValue);
            error = retVal.Body.error;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Conexion3.ServiceWeb.closeConexionResponse> Conexion3.ServiceWeb.WebServicePruebaSoap.closeConexionAsync(Conexion3.ServiceWeb.closeConexionRequest request) {
            return base.Channel.closeConexionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Conexion3.ServiceWeb.closeConexionResponse> closeConexionAsync(string error) {
            Conexion3.ServiceWeb.closeConexionRequest inValue = new Conexion3.ServiceWeb.closeConexionRequest();
            inValue.Body = new Conexion3.ServiceWeb.closeConexionRequestBody();
            inValue.Body.error = error;
            return ((Conexion3.ServiceWeb.WebServicePruebaSoap)(this)).closeConexionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Conexion3.ServiceWeb.insertarDrugstoreResponse Conexion3.ServiceWeb.WebServicePruebaSoap.insertarDrugstore(Conexion3.ServiceWeb.insertarDrugstoreRequest request) {
            return base.Channel.insertarDrugstore(request);
        }
        
        public string insertarDrugstore(string Name, string thelephone) {
            Conexion3.ServiceWeb.insertarDrugstoreRequest inValue = new Conexion3.ServiceWeb.insertarDrugstoreRequest();
            inValue.Body = new Conexion3.ServiceWeb.insertarDrugstoreRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.thelephone = thelephone;
            Conexion3.ServiceWeb.insertarDrugstoreResponse retVal = ((Conexion3.ServiceWeb.WebServicePruebaSoap)(this)).insertarDrugstore(inValue);
            return retVal.Body.insertarDrugstoreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Conexion3.ServiceWeb.insertarDrugstoreResponse> Conexion3.ServiceWeb.WebServicePruebaSoap.insertarDrugstoreAsync(Conexion3.ServiceWeb.insertarDrugstoreRequest request) {
            return base.Channel.insertarDrugstoreAsync(request);
        }
        
        public System.Threading.Tasks.Task<Conexion3.ServiceWeb.insertarDrugstoreResponse> insertarDrugstoreAsync(string Name, string thelephone) {
            Conexion3.ServiceWeb.insertarDrugstoreRequest inValue = new Conexion3.ServiceWeb.insertarDrugstoreRequest();
            inValue.Body = new Conexion3.ServiceWeb.insertarDrugstoreRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.thelephone = thelephone;
            return ((Conexion3.ServiceWeb.WebServicePruebaSoap)(this)).insertarDrugstoreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Conexion3.ServiceWeb.personaRegistradaResponse Conexion3.ServiceWeb.WebServicePruebaSoap.personaRegistrada(Conexion3.ServiceWeb.personaRegistradaRequest request) {
            return base.Channel.personaRegistrada(request);
        }
        
        public int personaRegistrada(string Employee_Id) {
            Conexion3.ServiceWeb.personaRegistradaRequest inValue = new Conexion3.ServiceWeb.personaRegistradaRequest();
            inValue.Body = new Conexion3.ServiceWeb.personaRegistradaRequestBody();
            inValue.Body.Employee_Id = Employee_Id;
            Conexion3.ServiceWeb.personaRegistradaResponse retVal = ((Conexion3.ServiceWeb.WebServicePruebaSoap)(this)).personaRegistrada(inValue);
            return retVal.Body.personaRegistradaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Conexion3.ServiceWeb.personaRegistradaResponse> Conexion3.ServiceWeb.WebServicePruebaSoap.personaRegistradaAsync(Conexion3.ServiceWeb.personaRegistradaRequest request) {
            return base.Channel.personaRegistradaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Conexion3.ServiceWeb.personaRegistradaResponse> personaRegistradaAsync(string Employee_Id) {
            Conexion3.ServiceWeb.personaRegistradaRequest inValue = new Conexion3.ServiceWeb.personaRegistradaRequest();
            inValue.Body = new Conexion3.ServiceWeb.personaRegistradaRequestBody();
            inValue.Body.Employee_Id = Employee_Id;
            return ((Conexion3.ServiceWeb.WebServicePruebaSoap)(this)).personaRegistradaAsync(inValue);
        }
    }
}
